import React from 'react';
import './Jwellery.css';

const jewelryProducts = [
  {
    image: { filename: 'productimage',
     url: 'https://media.istockphoto.com/id/1658696488/photo/close-up-of-gold-and-diamond-necklace-with-pair-of-earrings.webp?b=1&s=170667a&w=0&k=20&c=xJB3FaTA9LtSoEv19ARUVvv6BQiYmpfYXqB65AzsmPU=' },
    title: 'Eternal Elegance Necklace',
    description: 'A timeless piece with sparkling diamonds all around',
    price: 4912.44,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/117547819/photo/gold-ring.jpg?s=612x612&w=0&k=20&c=19Sw-9jtMKtWL6rmYR8q7p8D3fphd8GWJtKaA5rIk5s=' },
    title: 'Golden Halo Ring',
    description: 'A stunning halo ring featuring a brilliant diamond at the center',
    price: 8589.09,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/1133737343/photo/beautiful-design-of-jewelry-fashion-accessories-for-women-and-lady-shiny-crystal-or-diamond.jpg?s=612x612&w=0&k=20&c=7UCHQQzjubsGWCf1ogS1KYiBVKtJceyhnFTVXBJF8SI=' },
    title: 'Mystic Blue Sapphire Earrings',
    description: 'Elegant sapphire drop earrings accented with a halo of diamonds',
    price: 8475.83,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/865548838/photo/3d-illustration-two-rose-and-yellow-gold-eternity-band-diamond-rings-with-reflection-and-shadow.jpg?s=612x612&w=0&k=20&c=zdoIF7OR6U3xDqr3x7bifP5rYQT6wc_Kp31GQjXp0cM=' },
    title: 'Rose Gold Infinity Bracelet',
    description: 'A delicate rose gold bracelet featuring an infinite loop of diamonds',
    price: 1750.0,
  },
  {
    image: { filename: 'productimage',
     url: 'https://media.istockphoto.com/id/516546125/photo/shell-necklace-on-white-background.jpg?s=612x612&w=0&k=20&c=0khXHezttoRK2vJTtarTcaa_GVkYdY71zvNnIEqPZZI=' },
    title: 'Vintage Pearl Choker',
    description: 'A classic choker necklace with lustrous pearls arranged in a single strand',
    price: 383.23,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/1458820614/photo/indian-traditional-jewellery-displayed-in-a-street-shop-for-sale-in-pune-maharashtra-indian.jpg?s=612x612&w=0&k=20&c=KbzCUIgZqwytJlCWctyg-DT9MPINo0IPxTd_H0PPtWM=' },
    title: 'Radiant Ruby Necklace',
    description: 'A dazzling necklace featuring radiant rubies and diamonds',
    price: 5291.89,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/815613202/photo/golden-ring.jpg?s=612x612&w=0&k=20&c=UzMjEjCL5Z90_h8D3BbWIWGt5yIFyrPvL9zN20_BN_E=' },
    title: 'Opulent Emerald Ring',
    description: 'An opulent ring with a central emerald stone surrounded by diamonds',
    price: 6734.5,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/157534346/photo/large-diamond-with-other-jewlery-on-black-background.jpg?s=612x612&w=0&k=20&c=-Mw-XBqUapV54Q5s3sx3Uap8ka73EtWyhclM8pLEslw=' },
    title: 'Elegant Sapphire Bracelet',
    description: 'A bracelet adorned with elegant sapphires in a beautiful design',
    price: 4521.3,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/149393363/photo/jewelry.jpg?s=612x612&w=0&k=20&c=Zv9GXBwkhboHKDbe4S7MOZLdCtHtC23WdvoH8VXV1Wk=' },
    title: 'Luminous Pearl Earrings',
    description: 'Charming earrings featuring luminous pearls and diamonds',
    price: 2187.75,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/898886766/photo/pendants-and-pink-opal-bead-embroidery.webp?b=1&s=170667a&w=0&k=20&c=jTalUQcCIXY1QT3a34S8Q5hpgDVj_c9B65pq40Ip3ls=' },
    title: 'Enchanted Topaz Pendant',
    description: 'An exquisite pendant featuring an enchanted topaz gemstone',
    price: 3894.2,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/173682940/photo/snowflake-christmas-ornament.jpg?s=612x612&w=0&k=20&c=YG_BwKYzx8LdcVU7hejGfk9SC6yXy-820yf6wTPwX0Y=' },
    title: 'Majestic Aquamarine Brooch',
    description: 'A majestic brooch adorned with aquamarine stones',
    price: 2750.3,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/511646917/photo/golden-diamond-ring-and-contemporary-diamond.webp?b=1&s=170667a&w=0&k=20&c=kzFE4mLFHszm5jV9pPiatEpS0a6Cc0DOPPxdn1h28Ls=' },
    title: 'Sophisticated Garnet Band',
    description: 'A sophisticated band with a row of garnet stones',
    price: 612.8,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/182222705/photo/broach-on-satin-background.jpg?s=612x612&w=0&k=20&c=gOpbUCBYfhn5YGdEiyDcTNbXO7TIVnTOtNEPcawMytI=' },
    title: 'Opulent Onyx Cuff',
    description: 'An opulent cuff bracelet with sleek onyx beauty and can be found in our online jewelry store. stones',
    price: 2945.6,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/466074553/photo/diamond-jewel-with-reflections-on-gold-background.jpg?s=612x612&w=0&k=20&c=hefS6WwbmY8d9sHjMSU-OjmOPN4nNUSVR2irAReJ5Kg=' },
    title: 'Charming Citrine Anklet',
    description: 'A charming anklet with sparkling citrine gemstones with pure diamond heart shape',
    price: 812.5,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/589977628/photo/pendant-on-chain.jpg?s=612x612&w=0&k=20&c=tCqRXB38fXP0aMAtcGmn7aAoxN8jMRvMsDKZiUfXzr0=' },
    title: 'Graceful Jade Locket',
    description: 'A graceful locket featuring a jade stone in an intricate design Ring jade Natural sparkling green color.',
    price: 1450.3,
  },
  {
    image: { filename: 'productimage', 
    url: 'https://media.istockphoto.com/id/1447170018/photo/girl-jewelry-accessories-pearl-peridot-and-pink-quartz-necklaces-on-display.jpg?s=612x612&w=0&k=20&c=a4V91bXwRB3-sjA_LBto0tm92AeWeo-AgMBNYGIz-uw=' },
    title: 'Turquoise Charm Necklace',
    description: 'A delightful necklace with turquoise charm pendantschain isolated over white',
    price: 1920.75,
  },
  {
    image: { filename: 'productimage', 
    url: 'https://media.istockphoto.com/id/610434240/photo/tiara-on-a-white-background.jpg?s=612x612&w=0&k=20&c=I3Nai-K7l_FLzdvstdyc4yPqCD4cdzTHZlzFsWQqkY0=' },
    title: 'Exquisite Zircon Tiara',
    description: 'An exquisite tiara adorned with dazzling zircon crown with diamonds isolated on white background stones',
    price: 6950.9,
  },
  {
    image: { filename: 'productimage',
     url: 'https://media.istockphoto.com/id/1570007999/photo/elegant-jewelry-set-jewellery-set-with-gemstones-jewelry-accessories-collage-product-still.jpg?s=612x612&w=0&k=20&c=atuG88xrjjEJFVbvnv38u5c4WzwTgSxFAjgne2yZ6yA=' },
    title: 'Radiant Amethyst Cufflinks',
    description: 'Radiant cufflinks featuring amethyst stones for a touch of luxury Neavy Blue',
    price: 899.99,
  },
  {
    image: { filename: 'productimage',
     url: 'https://media.istockphoto.com/id/546003198/photo/diamond-brooch-isolated-on-white.webp?b=1&s=170667a&w=0&k=20&c=goRvb3t9AzyF_-4_rl5fjjzT7JnFpCpB4KVSphwl7sk=' },
    title: 'Delicate Peridot Diadem',
    description: 'A delicate diadem adorned with stunning peridot stones Peridot is found globally and considered.',
    price: 3820.4,
  },
  {
    image: { filename: 'productimage',
     url: 'https://media.istockphoto.com/id/101576924/photo/necklace.jpg?s=612x612&w=0&k=20&c=DPhHDug0UeiVqvLWFsVyKLhJiVWv8zzkU2d200YchPg=' },
    title: 'Enchanted Quartz Chain',
    description: 'A magical chain necklace with quartz beads necklace with diamonds on a white background',
    price: 925.5,
  },
  {
    image: { filename: 'productimage',
     url: 'https://media.istockphoto.com/id/495595316/photo/jewelry.jpg?s=612x612&w=0&k=20&c=GtwNxJz6un2z6e6lygIJPRyAvIGdcrJBKVPEAhPuZoY=' },
    title: 'Charming Aquamarine Locket',
    description: 'A charming locket with an aquamarine stone at its center',
    price: 1430.6,
  },
  {
    image: { filename: 'productimage',
     url: 'https://media.istockphoto.com/id/1170961808/photo/christmas-decor-closeup-on-a-white-background-isolated-image.jpg?s=612x612&w=0&k=20&c=J5DI9Yycxwu6SqBRI32IPNO7pf5S31LVQpudCyrwvA4=' },
    title: 'Opulent Ruby Charm',
    description: 'An opulent charm bracelet adorned with ruby stones Christmas decor on a white .',
    price: 2780.4,
  },
  {
    image: { filename: 'productimage',
     url: 'https://media.istockphoto.com/id/182234057/photo/fashion-bracelet-on-white.jpg?s=612x612&w=0&k=20&c=W_PNunO5cG-V_IJD8PMssOtG5p6l9JcolprDKq3JcOg=' },
    title: 'Luminous Emerald Anklet',
    description: 'A luminous anklet featuring stunning emerald stones',
    price: 1675.8,
  },
  {
    image: { filename: 'productimage',
     url: 'https://media.istockphoto.com/id/920744062/photo/ancient-style-earrings.jpg?s=612x612&w=0&k=20&c=AX_7cwo7XgQ3dKUgTpJAbEL4F6sa_xfyzooibzD4APw=' },
    title: 'Elegant Sapphire Chain',
    description: 'An elegant chain necklace with sparkling sapphires',
    price: 4321.7,
  },
  {
    image: { filename: 'productimage',
     url: 'https://media.istockphoto.com/id/465264878/photo/brooch-flower-accessory.webp?b=1&s=170667a&w=0&k=20&c=Gc1ufUdqtmMzebGEG07xtV5tt4S5A4xW_7ron-srUrI=' },
    title: 'Delicate Pearl Brooch',
    description: 'A delicate brooch with pearls arranged in a floral pattern',
    price: 1475.3,
  },
  {
    image: { filename: 'productimage',
     url: 'https://media.istockphoto.com/id/895454342/photo/gold-brooch-flower-with-gems-and-moon-stone-isolated-on-black.jpg?s=612x612&w=0&k=20&c=1a-bw-COqVYzSSqDGgVvOKWGd-Of6n3ccn-lMz3zD7w=' },
    title: 'Exquisite Topaz Cuff',
    description: 'An exquisite cuff bracelet with topaz stones',
    price: 3140.5,
  },
  {
    image: { filename: 'productimage',
     url: 'https://media.istockphoto.com/id/1448022041/photo/set-of-golden-set-with-diamonds-over-black-background.jpg?s=612x612&w=0&k=20&c=dgeBxs7wPrtKdqkgUrLuLyTgsNB4eOU4ceTSVZFOv28=' },
    title: 'Majestic Garnet Pendant',
    description: 'A majestic pendant with a central garnet stone',
    price: 4850.9,
  },
  {
    image: { filename: 'productimage',
     url: 'https://media.istockphoto.com/id/489379862/photo/various-womens-gold-jewelry.jpg?s=612x612&w=0&k=20&c=tlMj3wDKONjHCrmgeoptxr3ruQJub-lX7v4fvt9vHRQ=' },
    title: 'Opulent Onyx Band',
    description: 'An opulent band with sleek onyx stones',
    price: 1975.2,
  },
  {
    image: { filename: 'productimage', 
    url: 'https://media.istockphoto.com/id/1483053558/photo/yellow-sapphire-ring-with-brown-diamonds-and-gemstones-jewelry-in-white-gold-with-gems.webp?b=1&s=170667a&w=0&k=20&c=zvs0WgU8nPnyCY5XuR87wsxxENT1uXBxq0aSAR6fXYM=' },
    title: 'Sophisticated Citrine Earrings',
    description: 'Sophisticated earrings featuring citrine stones',
    price: 1899.5,
  },
  {
    image: { filename: 'productimage',
     url: 'https://media.istockphoto.com/id/1215637053/photo/rings-and-jewelry-with-diamonds-and-gemstones-ruby-and-sapphire.jpg?s=612x612&w=0&k=20&c=t72pmO8W9T02wak0ows5HqlsL9afdlXqBTLD6IFVCgo=' },
    title: 'Charming Jade Tiara',
    description: 'A charming tiara adorned with jade stones',
    price: 5120.8,
  },
  {
    image: { filename: 'productimage',
     url: 'https://media.istockphoto.com/id/625555798/photo/semigem-necklace-with-bright-crystals-jewelry.jpg?s=612x612&w=0&k=20&c=o0qTi0veTd371HQcassPtYQf_IXmwSBuqVeWk9mAjI4=' },
    title: 'Enchanted Turquoise Rosary',
    description: 'A magical rosary necklace with turquoise beads',
    price: 920.4,
  },
  {
    image: { filename: 'productimage',
     url: 'https://media.istockphoto.com/id/1200356005/photo/jewelry.jpg?s=612x612&w=0&k=20&c=BlpiZ6dwD9FH4dQAFQcTlkjsPZRXY2CZKOUS8hU_UV0=' },
    title: 'Radiant Moonstone Charm',
    description: 'A radiant charm bracelet adorned with moonstone gems',
    price: 2950.6,
  },
  {
    image: { filename: 'productimage',
     url: 'https://media.istockphoto.com/id/894632276/photo/american-diamond-necklace-closeup-image-on-black-background.jpg?s=612x612&w=0&k=20&c=nw8JuTzbgCyIjFvSdlsdbIa3b5ZLzzZtcj2vwqtlpr8=' },
    title: 'Opulent Zircon Anklet',
    description: 'An opulent anklet with zircon stones with white stone hard stones and golden chains.',
    price: 1640.5,
  },
  {
    image: { filename: 'productimage', 
    url: 'https://media.istockphoto.com/id/515221511/photo/engagement-ring-with-diamond-on-white-jewelry-background.jpg?s=612x612&w=0&k=20&c=7YC4sRHdUARBGnTPpojp8mUkcY8k3VGm2zGazqengFc=' },
    title: 'Delicate Amethyst Band',
    description: 'A delicate band with amethyst stones and Diamond nug',
    price: 789.4,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/1540257812/photo/golden-earrings-and-jewelry-box-on-table-close-up.jpg?s=612x612&w=0&k=20&c=lKz-wYrOHQMCGGUO8BZysZrMzugeT-wtHEyRuhwHlWE=' },
    title: 'Exquisite Pearl Earrings',
    description: 'Exquisite earrings featuring pearls and diamonds',
    price: 2150.8,
  },
  {
    image: { filename: 'productimage', url: 'https://images.unsplash.com/photo-1615653868225-ce1d35288ec3?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8Q2hhcm1pbmclMjBBcXVhbWFyaW5lJTIwVGlhcmF8ZW58MHx8MHx8fDA%3D' },
    title: 'Charming Aquamarine Tiara',
    description: 'A charming tiara adorned with aquamarine stones',
    price: 4950.9,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/1092699280/photo/white-gold-pendant-with-peridot-and-diamonds.jpg?s=612x612&w=0&k=20&c=gtsjOfr1gnecY3gLV8k0lnIHakHVdlw3pqCtxbf9SCA=' },
    title: 'Opulent Garnet Locket',
    description: 'An opulent locket with a central garnet stone and made shape in heart green diamond',
    price: 2675.3,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/489832220/photo/gold-earrings.jpg?s=612x612&w=0&k=20&c=ZxGa_hg1eDr99vZDzUySY8FUtueMLLrEuUMtmj7seB4=' },
    title: 'Majestic Jade Brooch',
    description: 'Gold earrings with emerald and gold earrings in the shape of a heart',
    price: 3480.5,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/618338992/photo/necklace-with-bright-crystals-jewelry.jpg?s=612x612&w=0&k=20&c=03X_kHrGpyBqeIrhDjPA72hqnXt0TCaTBTcWczwTn2w=' },
    title: 'Sophisticated Citrine Chain',
    description: 'A sophisticated chain necklace with citrine stones',
    price: 1490.7,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/1143411253/photo/beautiful-fashionable-gold-and-silver-jewelry-and-accessories-realistic-set-isolated-on-white.jpg?s=612x612&w=0&k=20&c=cTev1jux9DmFSkn2ThqPfUUy6_BKoFuLWDCsPL1Y3-E=' },
    title: 'Elegant Sapphire Anklet',
    description: 'An elegant anklet featuring sapphire stones',
    price: 1760.4,
  },
  {
    image: { filename: 'productimage', 
    url: 'https://media.istockphoto.com/id/623421832/photo/gold-ring-earrings-and-chains.jpg?s=612x612&w=0&k=20&c=OYjVq0Q2SO2yVUC37P_lrkqU-K_gmC4cMYjxUIgG098=' },
    title: 'Luminous Turquoise Pendant',
    description: 'A luminous pendant with a turquoise stone',
    price: 2440.8,
  },
  {
    image: { filename: 'productimage', 
    url: 'https://media.istockphoto.com/id/135360581/photo/diamond-necklace-with-ear-ring.jpg?s=612x612&w=0&k=20&c=5AwVu6IcZgmaeKAxbxpN4jrBx9eATtwXMnOPpOt6z08=' },
    title: 'Exquisite Ruby Brooch',
    description: 'An exquisite brooch featuring ruby stones full set diamond chain',
    price: 3810.5,
  },
  {
    image: { filename: 'productimage',
     url: 'https://media.istockphoto.com/id/506172756/photo/beautiful-shiny-earrings-on-the-vintage-background.jpg?s=612x612&w=0&k=20&c=rFamMGu2fg6oRtmFMIrFfxN-Jc6XDspXJ8cevCfU2cE=' },
    title: 'Majestic Onyx Earrings',
    description: 'Majestic earrings with onyx pure white Nuge stones with Box. ',
    price: 2350.2,
  },
  {
    image: { filename: 'productimage',
     url: 'https://media.istockphoto.com/id/610554744/photo/bracelet-with-pearls-and-pendants-isolated-on-white.jpg?s=612x612&w=0&k=20&c=R6-7bGkCngrgYQ01etf7N7YMHMDuWX-D6jYw9hzR2NQ=' },
    title: 'Charming Zircon Cuff',
    description: 'A charming cuff bracelet with zircon stones bracelet with on white.',
    price: 1925.6,
  },
  {
    image: { filename: 'productimage', 
    url: 'https://media.istockphoto.com/id/615800860/photo/diamond-pendant-isolated-on-white.jpg?s=612x612&w=0&k=20&c=QbszCuuGzgKWoPBUWNwAcjB0MI1TRJo--wdXltP82l8=' },
    title: 'Delicate Peridot Locket',
    description: 'A delicate locket with a peridot stone Fancy American diamond Chan Pendant jewelry',
    price: 1730.4,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/1194657121/photo/heart-shaped-diamond-earrings-and-pendants-on-the-black-ground.webp?b=1&s=170667a&w=0&k=20&c=wQVRHj6Iyy7QnBMDMiIPIpOJOpI4gBYJqYpnrTHUQgE=' },
    title: 'Opulent Sapphire Cufflinks',
    description: 'Opulent cufflinks featuring sapphire stones Beautiful diamond turbine bracelet',
    price: 1199.5,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/134960724/photo/pearl-necklaces.jpg?s=612x612&w=0&k=20&c=Ym2_5zTGqAyN6BYJpHfrKEhIXPcLzCNYbNjT3LnhmFI=' },
    title: 'Exquisite Moonstone Bracelet',
    description: 'An exquisite bracelet with moonstone gems Pearl necklaces. Shallow depth of foc',
    price: 3490.3,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/599905350/photo/gold-jewelry.jpg?s=612x612&w=0&k=20&c=aZf3zbh5HjFqPGgTCGE564jUaRlrpnohMOvRu7inoSk=' },
    title: 'Radiant Emerald Chain',
    description: 'A radiant chain necklace with emerald stones Gold jewelry on a white background.',
    price: 4680.4,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/475155988/photo/diamond-collections-of-jewelry-gems.jpg?s=612x612&w=0&k=20&c=a3PpI0sknhLIhZczbnIIPJCC_xphzaNlhozdgUmTH3o=' },
    title: 'Elegant Amethyst Band',
    description: 'An elegant band with amethyst stones',
    price: 830.5,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/627500580/photo/different-a-gold-earrings.jpg?s=612x612&w=0&k=20&c=-FwSX-ER09f0GV0oz493RXxUIb4Cu12XIKf50dvjufI=' },
    title: 'Luminous Garnet Pendant',
    description: 'A luminous pendant featuring a garnet stone',
    price: 2550.6,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/619374196/photo/necklace-with-bright-crystals-jewelry-and-earrings.jpg?s=612x612&w=0&k=20&c=MueAGmEQwaxUkoAZy6p01xrK1mehb5DZ9dGCV4Ogd10=' },
    title: 'Opulent Ruby Locket',
    description: 'An opulent locket with a central ruby stone gold earrings with violet.',
    price: 2975.4,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/187748213/photo/gold-earrings-with-shiny-crystals.jpg?s=612x612&w=0&k=20&c=9JusRCcoX6mZ0wy1IJP_8p4osa-S5Ml9J2hruVPLWik=' },
    title: 'Delicate Citrine Brooch',
    description: 'A delicate brooch with citrine stones',
    price: 1830.5,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/1291385537/photo/luxury-elegant-baroque-pearl-golden-necklace-on-white-background.jpg?s=612x612&w=0&k=20&c=4heilqJ2t29GN2d0ewNByg66tbQTcAM6X047Sfx0izM=' },
    title: 'Sophisticated Onyx Anklet',
    description: 'A sophisticated anklet with onyx stones',
    price: 1620.3,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/489813954/photo/fine-silver-rings-and-unusual-silver-chain.jpg?s=612x612&w=0&k=20&c=1uRUbLBnbma74T-IvdmoYh2rZu1EMDGoY9q_j9vg5V8=' },
    title: 'Majestic Pearl Earrings',
    description: 'Majestic earrings featuring pearls and diamonds',
    price: 2250.4,
  },
  {
    image: { filename: 'productimage',
    url: 'https://media.istockphoto.com/id/154957086/photo/gem-rings.jpg?s=612x612&w=0&k=20&c=ykFJXth5tGavR3kps86SoUQURLv8uyntJBJJIoPExaM=' },
    title: 'Opulent Aquamarine Cuff',
    description: 'An opulent cuff bracelet with aquamarine stones',
    price: 3290.7,
  },
  {
    image: { filename: 'productimage',
     url: 'https://media.istockphoto.com/id/471379845/photo/old-diadem-on-white-background.jpg?s=612x612&w=0&k=20&c=mmhbQVF9oiynMlTLya3-5s3jfP_mX30FzdPlwWfdFiY=' },
    title: 'Radiant Topaz Tiara',
    description: 'A radiant tiara adorned with topaz Old diadem on white stones',
    price: 5450.6,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/1132538797/photo/jade-on-gold-ring-with-diamond.jpg?s=612x612&w=0&k=20&c=QL480jM6VSLv08r6DH_sKk4wvBD8zlaD6kM-lk5RWfg=' },
    title: 'Charming Jade Pendant',
    description: 'A charming pendant with a jade stone with Quality white ring.',
    price: 2180.9,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/1221289204/photo/beautiful-gold-and-gems-necklace-isolated-on-white-background.jpg?s=612x612&w=0&k=20&c=S_8Wn5qci5uVJcrPBql4oLZtCsX2TgE80TdckCeaRWk=' },
    title: 'Delicate Zircon Chain',
    description: 'A delicate chain necklace with zircon Thailand, Chain - Object, gold, Beauty stones',
    price: 1405.3,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/510382866/photo/gold-brooch-with-diamonds-on-a-white-background.jpg?s=612x612&w=0&k=20&c=dILTXRnXjwTd_yI5vbKWqp7KAyq-cmCwDNq8OzpUfmE=' },
    title: 'Opulent Moonstone Brooch',
    description: 'An opulent brooch with moonstone gems gold brooch with diamonds.',
    price: 3875.4,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/1135997379/photo/jewelry-diamonds-with-and-gemstone-emerald-ruby-and-sapphire-ring-earrings.jpg?s=612x612&w=0&k=20&c=SzpCDVRyyqtmpVY0Rlt5hsgpuNtu73_Q1JCFO67JKVU=' },
    title: 'Sophisticated Garnet Cufflinks',
    description: 'Sophisticated cufflinks with garnet stones and Sapphire ring jewelry',
    price: 1060.3,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/923613954/photo/white-gold-ring-with-citrine-peridot-blue-topaz-pink-tourmaline-and-diamonds-on-soft-white.jpg?s=612x612&w=0&k=20&c=BbiX8w5V98KmhFqbW_L98nqOhDAh_80SXG3rnPxbjWU=' },
    title: 'Elegant Turquoise Band',
    description: 'An elegant band with turquoise White gold ring with stones',
    price: 710.8,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/2130099844/photo/elegant-jewelry-set-jewellery-set-with-gemstones-jewelry-accessories-collage-product-still.jpg?s=612x612&w=0&k=20&c=xk6oPTxc8wkGgtAr9cMp4Az4q7wfu9VpmT_FyO3Q29E=' },
    title: 'Luminous Sapphire Pendant',
    description: 'A luminous pendant with a sapphire Ring, necklace and earrings. stone',
    price: 2670.4,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/172515066/photo/christmas-jewels-with-flake.jpg?s=612x612&w=0&k=20&c=4hMXkHUGGb05bXOmNFpVGWwi5veNAzbMn37GHIywTAc=' },
    title: 'Opulent Pearl Charm',
    description: 'An opulent charm bracelet with pearls ewels with pearls and snowflakes',
    price: 2030.5,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/176987979/photo/gold-crown-isolated-on-the-white.jpg?s=612x612&w=0&k=20&c=8eMw4A2zn1Fn8HALHwN7HJP5UhzbbzZPcBC6rVU8Q_Q=' },
    title: 'Majestic Ruby Tiara',
    description: 'A majestic tiara adorned with ruby Gold crown isolated on the white stones',
    price: 4920.8,
  },
  {
    image: { filename: 'productimage',
     url: 'https://media.istockphoto.com/id/1135998146/photo/earrings-ring-jewelry-diamonds-with-and-gemstone-emerald-ruby-and-sapphire.jpg?s=612x612&w=0&k=20&c=eNL8rh_gsVfPT5Y-1LsadY88UzWn3DWspUCoRja3FoI=' },
    title: 'Sophisticated Onyx Locket',
    description: 'jewelry diamonds with and gemstone emerald ruby and Sapphire ring earrings',
    price: 1895.7,
  },
  {
    image: { filename: 'productimage',
     url: 'https://media.istockphoto.com/id/985714074/photo/gold-brooch-feather-with-diamonds-isolated-on-silk.webp?b=1&s=170667a&w=0&k=20&c=g7ox2vDZP2R_DBkb7pwHRQwV2H_jTc3RMT1Gdl4y2uU=' },
    title: 'Delicate Amethyst Brooch',
    description: 'A delicate brooch with amethyst gold brooch feather with diamonds isolated on silk stones',
    price: 1780.4,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/862022134/photo/pearl-neclace-set.webp?b=1&s=170667a&w=0&k=20&c=_zvYT-55JjkUQv7PA6iwaNRelidMTKMWI6I2T6J-uAc=' },
    title: 'Exquisite Emerald Chain',
    description: 'An exquisite chain necklace with emerald Indian antique pearl neclace set stones',
    price: 4890.9,
  },
  {
    image: { filename: 'productimage',
     url: 'https://media.istockphoto.com/id/515781387/photo/tiara-and-flowers.jpg?s=612x612&w=0&k=20&c=fUKSg2r0_-w9s9a4hRg8aF3WpBA-FlBlQ-mEmphCjT8=' },
    title: 'Radiant Citrine Cuff',
    description: 'A radiant cuff bracelet with citrine A sparking tiara and floral background Pink Rose with white stones',
    price: 2560.5,
  },
  {
    image: { filename: 'productimage',
     url: 'https://media.istockphoto.com/id/473749998/photo/designer-diamond-bracelet.jpg?s=612x612&w=0&k=20&c=gCw6PUtUxKkVfSLUQz1Sm47ElZPYHISdbw19k-TLjd0=' },
    title: 'Charming Garnet Band',
    description: 'A charming band with garnet Designer white background, clipping paths included',
    price: 740.6,
  },
  {
    image: { filename: 'productimage',
     url: 'https://media.istockphoto.com/id/1140708770/photo/woman-brooches-great-collection-of-brooches-of-various-shapes-and-sizes-with-pearls-and.webp?b=1&s=170667a&w=0&k=20&c=nYSWyvjZY47ux2bPSddnw77xEJwgsY_DKNpJAqByw_w=' },
    title: 'Opulent Sapphire Brooch',
    description: 'Woman brooches. Great collection of brooches of various shapes and sizes',
    price: 3890.3,
  },
  {
    image: { filename: 'productimage',
     url: 'https://media.istockphoto.com/id/1498014838/photo/owl-necklace-is-surrounded-by-the-elegant-lady-jewellery-set.webp?b=1&s=170667a&w=0&k=20&c=DuBllP1pd2pKT1HRHLCVRLXaEXjWDLYtrtTL546e2TQ=' },
    title: 'Elegant Jade Earrings',
    description: 'Elegant Lady Jewellery Set, Isolated on the Black Background which has The Gold Bracelet.',
    price: 2350.2,
  },
  {
    image: { filename: 'productimage', 
    url: 'https://media.istockphoto.com/id/2130131057/photo/elegant-jewelry-set-jewellery-set-with-gemstones-jewelry-accessories-collage-product-still.webp?b=1&s=170667a&w=0&k=20&c=XIu-Pj9TecVnXAiOmoFIJU16pfjDKs_yeD3twQAMtiQ=' },
    title: 'Luminous Zircon Pendant',
    description: 'A luminous pendant with a zircon  Product still life concept. Ring, necklace.',
    price: 2290.6,
  },
  {
    image: { filename: 'productimage',
     url: 'https://media.istockphoto.com/id/1295602853/photo/bracelets.jpg?s=612x612&w=0&k=20&c=WCe5GfhN7XWzuIRRQvWGPmRLwN9koZStlPABgfq4j4k=' },
    title: 'Exquisite Moonstone Anklet',
    description: 'Collection of natural mineral gemstone beads bracletes on natural neutral background',
    price: 1680.7,
  },
  {
    image: { filename: 'productimage', 
    url: 'https://media.istockphoto.com/id/1044903252/photo/ancient-style-necklace-and-earrings.jpg?s=612x612&w=0&k=20&c=8S1mTj2MQ4DwM5t62_NCVmmalUIoSMRvjjmxJuPy2ZA=' },
    title: 'Majestic Ruby Charm',
    description: 'Ancient style necklace and earrings isolated  Product isolation earrings,on a white background.',
    price: 3020.5,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/176230905/photo/treasure.jpg?s=612x612&w=0&k=20&c=-mM2rC5bYB5CDiEnOWFYRXxl8KVDfDxP1ncDi6KjPgk=' },
    title: 'Opulent Pearl Band',
    description: 'An opulent band with pearls treasure isolated on a white background,treasure as a background closeup',
    price: 980.9,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/1053354428/photo/beautiful-design-of-jewelry-fashion-accessories-for-women-and-lady-shiny-crystal-or-diamond.webp?b=1&s=170667a&w=0&k=20&c=1C5m-cgDkxYtTTqGU0JOTIOHOZLuwDGutvc-pEIJyzA=' },
    title: 'Delicate Topaz Earrings',
    description: 'Beautiful Design of Jewelry Fashion Accessories for Women and lady Shiny crystal ',
    price: 2120.3,
  },
  {
    image: { filename: 'productimage', 
    url: 'https://media.istockphoto.com/id/173042373/photo/quinceanera-crown.webp?b=1&s=170667a&w=0&k=20&c=RRNs4Em9aTAJWY7_r9st0JtN5wnk0vx5JyqF686kLto=' },
    title: 'Charming Turquoise Tiara',
    description: 'A charming tiara adorned with turquoise stones',
    price: 4980.8,
  },
  {
    image: { filename: 'productimage',
     url: 'https://media.istockphoto.com/id/473822110/photo/jewelry.jpg?s=612x612&w=0&k=20&c=BKDs2BgwjSo7Yu37ffkwmj-Q9Ls1cE1yP_n_d8FdP1M=' },
    title: 'Sophisticated Onyx Pendant',
    description: 'A sophisticated pendant with an onyx stone with neckless and earring.',
    price: 2160.7,
  },
  {
    image: { filename: 'productimage',
     url: 'https://media.istockphoto.com/id/1046329704/photo/ancient-style-necklace.jpg?s=612x612&w=0&k=20&c=nAWjan7dLj6WSZLv7Q2B_UCN7fv9ixS4MvmlSVk8RU8=' },
    title: 'Exquisite Amethyst Locket',
    description: 'Ancient style necklace isolated on a white background.',
    price: 3120.4,
  },
  {
    image: { filename: 'productimage',
     url: 'https://media.istockphoto.com/id/502013736/photo/jewellery-market-display.jpg?s=612x612&w=0&k=20&c=dBnI5usAFqWnxlQW6Q1JEZ7wxuSti1yl5EcSSNjvv0o=' },
    title: 'Elegant Garnet Chain',
    description: 'An elegant chain necklace with garnet Jewellery market display stones',
    price: 1900.5,
  },
  {
    image: { filename: 'productimage', url: 'https://media.istockphoto.com/id/173615427/photo/jewelry.jpg?s=612x612&w=0&k=20&c=WbKYdCve1ODoVa2_q_gytnHmFBwQkVeturMbtbspuYQ=' },
    title: 'Radiant Pearl Cuff',
    description: 'A radiant cuff bracelet with pearls and made pure golden with fixable diamond short stone rings ,neckless jewelry ',
    price: 2650.7,
  },
  {
    image: { filename: 'productimage',
     url: 'https://media.istockphoto.com/id/937236896/photo/beautiful-design-of-jewelry-fashion-accessories-for-women-and-lady-shiny-crystal-or-diamond.webp?b=1&s=170667a&w=0&k=20&c=yrigVwSeV8DJ67QS9m07mWptg5DbnyBkmh4NEVH3a-A=' },
    title: 'Opulent Jade Anklet',
    description: 'An opulent anklet with jade stones Women and lady Shiny crystal or diamond best Accessories',
    price: 1550.4,
  },
  {
    image: { filename: 'productimage',
     url: 'https://media.istockphoto.com/id/657161042/photo/gold-earrings-in-the-shape-of-a-horseshoe-and-a-delicate-ring-with-large-topaz.webp?b=1&s=170667a&w=0&k=20&c=mgLAae_75DkarcI1VmuPiVWUR-xwuukfGrl9CQKteE8=' },
    title: 'Delicate Citrine Pendant',
    description: 'A delicate pendant with a citrine stone Topaz surrounded by golden chains',
    price: 2470.5,
  },
  {
    image: { filename: 'productimage', 
    url: 'https://media.istockphoto.com/id/1337979277/photo/set-of-diamond-gemstone-beautiful-wedding-engagement-rings.webp?b=1&s=170667a&w=0&k=20&c=kVXTv4BDKiijJtSjLJgxsQWgB1yiMZ-b4AyupVTcdBg=' },
    title: 'Sophisticated Sapphire Band',
    description: ' Jewelry or jewelry shop setup for selling fashion accessories or fine jewelry.',
    price: 850.9,
  },
  
];

function JewelryProducts() {
  return (
    <>
    <h1 className='Heading Tenor'>"Our Jewelry Collection"</h1>
    <div className='Main'>
    {jewelryProducts.map((product, index) => (
      <div key={index} className="product">
        <img src={product.image.url} alt={product.title} />
        <h2>{product.title}</h2>
        <p>{product.description}</p>
        <h3>Rs {product.price.toFixed(2)}</h3>
       <a href=""><button className="add-to-cart" style={{backgroundColor:"#007bff" }}>Purchase now</button></a> 

      </div>
    ))}
  </div>
  </>
  );
}
export default JewelryProducts;
